version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
      - RABBIT_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
    ports:
      - 9229:9229

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672