version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment:
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - RABBIT_URL=amqp://rabbitmq
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_URL=postgres://face_fucker:123456@postgres/face_fucker_bot
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - DEBUG=${DEBUG}
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
    ports:
      - 9229:9229

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=face_fucker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=face_fucker_bot