version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      - NODE_ENV=development
      - REDIS_HOST=redis
      - BOT_TOKEN=${BOT_TOKEN}
      - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads