version: '3.7'

services:
  app:
    image: registry.gitlab.com/yanislav-igonin/face_fucker_bot:latest
    networks:
      - web
    environment: 
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - RABBIT_URL=${RABBIT_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_URL=${POSTGRES_URL}
      - DATABASE_LOG=false
      - DATABASE_SYNC=false
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - IS_WEBHOOK_DISABLED=false
    volumes:
      - /root/bots/face_fucker_bot/uploads:/usr/src/app/uploads
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.docker.network: "web"

        traefik.http.services.face_fucker_bot.loadbalancer.server.port: ${WEBHOOK_PORT}

        traefik.http.middlewares.face_fucker_bot-stripprefix.stripprefix.prefixes: "/admin"

        traefik.http.routers.face_fucker_bot-secure.entrypoints: "https"
        traefik.http.routers.face_fucker_bot-secure.rule: "Host(`igonin.dev`) && PathPrefix(`/bots`)"
        traefik.http.routers.face_fucker_bot-secure.tls: "true"
        traefik.http.routers.face_fucker_bot-secure.service: "face_fucker_bot"
        traefik.http.routers.face_fucker_bot-secure.middlewares: "face_fucker_bot-stripprefix"

networks:
  web:
    driver: overlay
    external: true
