version: '3.7'

services:
  app:
    image: registry.gitlab.com/yanislav-igonin/face_fucker_bot:latest
    networks:
      - web
    environment: 
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - RABBIT_URL=${RABBIT_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_URL=${POSTGRES_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - DEBUG=${DEBUG}
    volumes:
      - /root/face_fucker_bot/uploads:/usr/src/app/uploads
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == worker
          - node.hostname == bots
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:${WEBHOOK_URL}"
        traefik.port: ${WEBHOOK_PORT}

networks:
  web:
    driver: overlay
    external: true