version: '3.7'

services:
  app:
    image: docker.pkg.github.com/yanislav-igonin/face-fucker-bot/face-fucker-bot::latest
    networks:
      - web
    environment: 
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - RABBIT_URL=${RABBIT_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_URL=${POSTGRES_URL}
      - DATABASE_LOG=false
      - DATABASE_SYNC=false
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - IS_WEBHOOK_DISABLED=${IS_WEBHOOK_DISABLED}
    volumes:
      - /root/bots/face-fucker-bot/uploads:/usr/src/app/uploads
    deploy:
      resources:
        limits:
          cpus: '0.90'
          memory: 1024M
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.docker.network: "web"

        traefik.http.services.face-fucker-bot.loadbalancer.server.port: ${WEBHOOK_PORT}

        traefik.http.routers.face-fucker-bot-secure.entrypoints: "https"
        traefik.http.routers.face-fucker-bot-secure.rule: "Host(`${WEBHOOK_HOST}`) && PathPrefix(`${WEBHOOK_PATH}`)"
        traefik.http.routers.face-fucker-bot-secure.tls: "true"
        traefik.http.routers.face-fucker-bot-secure.service: "face-fucker-bot"

networks:
  web:
    driver: overlay
    external: true
