version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./images:/usr/src/app/images