version: '3.7'
services:
  bot:
    image: registry.gitlab.com/yanislav-igonin/face_fucker_bot:latest
    environment: 
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
      - RABBIT_URL=${RABBIT_URL}
    volumes:
      - ./uploads:/usr/src/app/uploads
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: on-failure
        window: 10s
      placement:
        constraints:
          - node.role == worker
          - node.host == bots